CREATE TABLE public.hot_scrapes
(
    author varchar,
    author_fullname varchar,
    author_patreon_flair varchar,
    author_premium varchar,
    body varchar,
    can_gild varchar,
    can_mod_post varchar,
    controversiality varchar,
    created varchar,
    created_utc varchar,
    depth varchar,
    downs varchar,
    fullname varchar,
    id varchar,
    is_root varchar,
    is_submitter varchar,
    link_id varchar,
    name varchar,
    no_follow varchar,
    parent_id varchar,
    permalink varchar,
    score varchar,
    submission varchar,
    subreddit varchar,
    subreddit_id varchar,
    total_awards_received varchar,
    ups varchar,
    time_gathered varchar
);

CREATE TABLE public.posts
(
    author                varchar,
    author_fullname       varchar,
    author_patreon_flair  varchar,
    author_premium        varchar,
    body                  varchar,
    can_gild              varchar,
    can_mod_post          varchar,
    controversiality      varchar,
    created               varchar,
    created_utc           varchar,
    depth                 varchar,
    downs                 varchar,
    fullname              varchar,
    id                    varchar,
    is_root               varchar,
    is_submitter          varchar,
    link_id               varchar,
    name                  varchar,
    no_follow             varchar,
    parent_id             varchar,
    permalink             varchar,
    score                 varchar,
    submission            varchar,
    subreddit             varchar,
    subreddit_id          varchar,
    total_awards_received varchar,
    ups                   varchar,
    time_gathered         varchar
);


CREATE TABLE public.user_comments
(
    archived varchar,
    author varchar,
    author_fullname varchar,
    author_premium varchar,
    body varchar,
    can_guild varchar,
    can_mod_post varchar,
    controversality varchar,
    created varchar,
    created_utc varchar,
    downs varchar,
    edited varchar,
    fullname varchar,
    gilded varchar,
    id varchar,
    id_from_url varchar,
    is_root varchar,
    is_submitter varchar,
    link_author varchar,
    link_id varchar,
    link_permalink varchar,
    link_title varchar,
    link_url varchar,
    locked varchar,
    "MISSING_COMMENT_MESSAGE" varchar,
    name varchar,
    no_follow varchar,
    num_comments varchar,
    over_18 varchar,
    parent_id varchar,
    permalink varchar,
    quarantine varchar,
    score varchar,
    score_hidden varchar,
    send_replies varchar,
    stickied varchar,
    "STR_FIELD" varchar,
    submission varchar,
    subreddit varchar,
    subreddit_id varchar,
    subreddit_name_prefixed varchar,
    subreddit_type varchar,
    total_awards_received varchar,
    ups varchar,
    time_gathered varchar
);


CREATE TABLE public.streamall
(
    author                varchar,
    author_fullname       varchar,
    author_patreon_flair  boolean,
    author_premium        boolean,
    body                  varchar,
    can_gild              boolean,
    can_mod_post          boolean,
    controversiality      integer,
    created               integer,
    created_utc           timestamptz,
    depth                 varchar,
    downs                 integer,
    fullname              varchar,
    id                    varchar,
    is_root               boolean,
    is_submitter          boolean,
    link_id               varchar,
    name                  varchar,
    no_follow             boolean,
    parent_id             varchar,
    permalink             varchar,
    score                 integer,
    submission            varchar,
    subreddit             varchar,
    subreddit_id          varchar,
    total_awards_received integer,
    ups                   integer,
    time_gathered_utc     timestamptz
);

CREATE TABLE public.stream_submissions_all
(
    author                  varchar,
    author_fullname         varchar,
    author_premium          boolean,
    author_patreon_flair    boolean,
    can_gild                boolean,
    can_mod_post            boolean,
    clicked                 boolean,
    comment_limit           integer,
    created                 integer,
    created_utc             timestamptz,
    downs                   integer,
    edited                  boolean,
    fullname                varchar,
    gilded                  integer,
    hidden                  boolean,
    hide_score              boolean,
    id                      varchar,
    is_crosspostable        boolean,
    is_meta                 boolean,
    is_original_content     boolean,
    is_reddit_media_domain  boolean,
    is_robot_indexable      boolean,
    is_self                 boolean,
    is_video                boolean,
    locked                  boolean,
    media_only              boolean,
    name                    varchar,
    no_follow               boolean,
    over_18                 boolean,
    permalink               varchar,
    pinned                  boolean,
    quarantine              boolean,
    saved                   boolean,
    selftext                varchar,
    shortlink               varchar,
    subreddit               varchar,
    subreddit_id            varchar,
    subreddit_name_prefixed varchar,
    subreddit_subscribers   integer,
    subreddit_type          varchar,
    thumbnail               varchar,
    title                   varchar,
    url                     varchar
);

select *
from public.stream_submissions_all
where author='AutoNewspaperAdmin'